version: "3.3"
services:
  db:
    image: percona:ps-8
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
    - /srv/data/nextcloud/db:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=${ADMIN_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USERNAME}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
    - nextcloud
    restart: unless-stopped
  redis:
    image: redis
    networks:
    - nextcloud
    restart: unless-stopped
  nextcloud:
    image: nextcloud:stable
    ports:
    - 8081:80 
    volumes:
    - /srv/data/nextcloud/data:/var/www/html
    - /srv/strange-data:/srv/strange-data
    - /srv/mark2:/srv/mark2
    environment:
    - NEXTCLOUD_ADMIN_USER=${ADMIN_USER}
    - NEXTCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    - NEXTCLOUD_TRUSTED_DOMAINS="10.0.0.13 cloud.strange.gg"
    - TRUSTED_PROXIES="172.19.0.1"
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_HOST=db
    - MYSQL_USER=${MYSQL_USERNAME}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - REDIS_HOST=redis
    networks:
    - nextcloud
    restart: unless-stopped
networks:
  nextcloud:
